server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestion_stagiaires?useSSL=false&serverTimezone=UTC
    username: root
    password: blomberg
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: fassassizoul4@gmail.com
    password: rakj ehmq oplu nelj
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
